# Generated by Django 3.1.4 on 2020-12-20 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
            ],
            options={
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(0)])),
                ('titulo', models.CharField(max_length=200)),
                ('publicacion', models.DateField(blank=True, null=True, verbose_name='fecha de publicacion')),
                ('portada', models.ImageField(blank=True, max_length=1000, upload_to='images/')),
                ('resumen', models.TextField(blank=True, max_length=500)),
                ('autor', models.ManyToManyField(to='mi_app.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha prestamo')),
                ('usuario', models.CharField(max_length=100)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.libro')),
            ],
        ),
    ]
