# Generated by Django 3.1.4 on 2020-12-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
