version: '3.7' 

services:
    nginx:
      image: nginx:alpine
      ports:
        - 80:80
      volumes:
        - ./conf:/etc/nginx/conf.d
        - ./app/static:/var/www/static 
      depends_on:
        - app
    app:
      build: .
      expose:
        - 5000
      depends_on: 
        - mongo
      volumes:
        - ./app:/app
      working_dir: /app
      command: gunicorn --bind 0.0.0.0:5000 app:app
    mongo:
      image: mongo:latest
      expose:
        - 27017
      volumes: 
        - ./dump:/dump
        - ./datos_db:/data/db
