version: '3.7' 

services:
    app:
      build: .
      ports:
        - 5000:5000
      depends_on: 
        - mongo
      volumes:
        - ./app:/app
      working_dir: /app
    mongo:
      image: mongo:latest
      volumes: 
        - ./dump:/dump
        - ./datos_db:/data/db
    mongo-express:
      image: mongo-express
      ports:
        - 8081:8081
